#pragma once

namespace Miami::Richard
{
enum Error
{
    OK = 0,
    INVARIANTS_VIOLATED = 0,

    CURSOR_ADVANCE_STOPPED_AT_BEGIN,
    CURSOR_ADVANCE_STOPPED_AT_END,

    CURSOR_GET_CURRENT_UNABLE_TO_GET_FROM_END,
};
}